### ISSUE TITLE
Workflow name not updated

### ISSUE THREAD

**Issue by muratmat** [PipedreamHQ/roadmap#109]
- from Workflows list, click on a workflow
- change the workflow name/title and click 'DEPLOY' button
- click on 'Workflows' (upper menu bar) in order to get back to the list of workflows

here's the bug: the list of workflows still shows the old name/title, not the updated one; in order to show the new name a tab reload from the browser titlebar is needed.

**Comment by dylburger** [comment]
@muratmat thanks for raising this. We noticed this internally, as well, and I'll let you know as soon as we've fixed it.

**Comment by dylburger** [comment]
A related bug prevents new workflows from showing up, as well (separate issue reported that I'm rolling into this issue)

**Comment by dylburger** [comment]
Related issue: new workflows are not showing up when you navigate back to the list of workflows (refresh also fixes)

**Comment by tjk** [comment]
Fixed! (Thanks for reporting)
