### ISSUE TITLE
HTTP Action - responseType as an Optional Param

### ISSUE THREAD

**Issue by rip3rs** [PipedreamHQ/roadmap#112]
**Is your feature request related to a problem? Please describe.**
Whenever I have to make a request (eg: fetch google maps static img) I have to do it programmatically because the HTTP action does not support an optional responseType param.

**Describe the solution you'd like**
Add as an Optional Param the responseTypes 

**Do you have a workaround?**
I can require nodejs action and use axios.

**Comment by dylburger** [comment]
@rip3rs this should be done. You'll need to add a new step and choose the **Send HTTP Request** action to get the new version. 

<img width="688" alt="Screen Shot 2019-11-22 at 2 59 06 PM" src="https://user-images.githubusercontent.com/242668/69466392-c739b900-0d38-11ea-9a21-e0d6b463fbb4.png">


Let me know if you see any issues!
