### ISSUE TITLE
[APP] Google Cloud Storage

### ISSUE THREAD

**Issue by sauvegardezvous** [PipedreamHQ/roadmap#115]
**Name of app / service**
google cloud storage 
https://cloud.google.com/storage/

**Link to developer documentation**
https://googleapis.dev/nodejs/storage/latest/index.html
https://cloud.google.com/storage/docs/apis?hl=en
https://cloud.google.com/storage/docs/reference/libraries
https://github.com/googleapis/nodejs-storage/tree/master/samples
https://developers.google.com/oauthplayground/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
yes,

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
no 

**Are there specific actions you'd use for this app?**
upload object to bucket 
makepublic 
makeprivate 
list bucket
list object
delete object
delete bucket

**Comment by dylburger** [comment]
@sauvegardezvous FYI this is progress. Part of the process requires confirmation from Google, so we're awaiting next steps on their end.

**Comment by dylburger** [comment]
Example workflow here: https://pipedream.com/@dylan/p_ljCdYd/edit
