### ISSUE TITLE
Safari: list of apps on Connect Account modal on /apps fails to scroll

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#134]
**Describe the bug**

On Safari, when you click the **Click Here to Connect an App** button on https://pipedream.com/apps , a model appears, but you cannot scroll through the list.

Does not appear to affect Firefox or Chrome on macOS.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.3

**Comment by mishavee** [comment]
Same problem on

- OS: Manjaro Linux
- Browser: Firefox
- Version: 73.0.1 (64-bit)

The modal also fails to scroll when:

- Scroll wheel on mouse
- Laptop touchpad scroll action
- Press Tab to put the cursor in the list. Press arrow keys, can get the cursor to go off into invisible territory.

![connect-app](https://user-images.githubusercontent.com/13145938/76041502-62803280-5fa6-11ea-883a-47d70665ab69.png)

**Comment by dylburger** [comment]
This should be fixed on all major browsers (Chrome, Safari, Firefox).
