### ISSUE TITLE
Not possible to unlink/change slack workspace

### ISSUE THREAD

**Issue by victorbjorklund** [PipedreamHQ/roadmap#147]
**Describe the bug**
Not possible to unlink/change slack workspace I linked my personal slack workspace for testing and that worked great. I can send a message from the node script:

const web = new WebClient(auths.slack.oauth_access_token)
await web.chat.postMessage({
  channel: "#general",
  text: message
})

But if I try to change the workspace it is not possible. Even if I change it keeps positing in my personal workspace instead of the workspace I want it to post to. I tried changing. I tried unlinking and then changing. I even tried unlinking and then making a copy of the script and then linking from the new copy. It keeps on posting in my personal account.

**Comment by dylburger** [comment]
@victorbjorklund this should be fixed now. Would you mind confirming whenever you have a moment?
