### ISSUE TITLE
[APP] Sendpulse

### ISSUE THREAD

**Issue by sauvegardezvous** [PipedreamHQ/roadmap#148]
**Name of app / service**
Sendpulse

**Link to developer documentation**
https://sendpulse.com/integrations/api
https://github.com/sendpulse/sendpulse-rest-api-node.js

**do you have a workaround?**
yes, doing manually

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
when a new subscriber is added, but there is a webhook to trigger that action. 

**Are there specific actions you'd use for this app?**
Retrieve General Information About a Specific Email Address
Viewing the Blacklist
Blacklisting an Email Address
Unsubscribe a Contact From a Defined Mailing List

**Comment by dylburger** [comment]
@sauvegardezvous I've added the SendPulse integration — let me know if this doesn't work for you. 

I'll be working through the actions separately.

**Comment by dylburger** [comment]
@sauvegardezvous also just added the 4 actions you requested.

**Comment by sauvegardezvous** [comment]
wow, awesome. thank you
