### ISSUE TITLE
I'd like a way to reset the data stored in $checkpoint for a specific workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#156]
Today, I can run the following code to manually reset the data stored in `$checkpoint`:

```javascript
$checkpoint = undefined
$end("cleared $checkpoint")
```

But ideally I'd like a way to clear `$checkpoint` from the UI. This is especially useful when I'm testing my workflow and have to consistently reset the data.

**Comment by tjk** [comment]
Checkpoints are now visible and updatable on the workflow settings page!!
