### ISSUE TITLE
Add Folders to categorize WFs

### ISSUE THREAD

**Issue by Juslesiasru** [PipedreamHQ/roadmap#158]
Hello,

That would be helpfull to be able to categorize the WFs.
I have many WF and i work by themes.

So can we have folders to stock them ?

Bye !

**Comment by sauvegardezvous** [comment]
good one.

**Comment by dylburger** [comment]
Hi @Juslesiasru @sauvegardezvous , we actually have a feature request for this here: #42 . I'm going to close this so we can consolidate feedback there.

Would y'all also mind +1'ing that feature request? I'll discuss this one with the team.
