### ISSUE TITLE
Improve deploy errors related to code errors

### ISSUE THREAD

**Issue by lardissone** [PipedreamHQ/roadmap#160]
**Describe the bug**
At the moment when you try to deploy a workflow and you have an error in your steps (invalid syntax for example), you get something like: `Error deploying pipeline: "Unexpected token (23:2)"`

**To Reproduce**
1. Go to edit a workflow
2. Add a syntax error (a missing `}` for example)
2. Click on 'Deploy'
3. See error message at bottom

**Expected behavior**
It should include at least the step name.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Safari/Chrome

**Comment by dylburger** [comment]
@lardissone we talked about this internally and we'll probably just prevent deploying altogether, telling you where you need to fix the syntax error before you can deploy. 

I'm hoping we can incorporate this into some other changes we're making, so we'll keep you updated.

**Comment by dylburger** [comment]
@lardissone we should now be preventing deploys until you fix syntax errors. It should also be clear where the error is, at what step. Let me know if this works for you or if you’re still seeing issues!

**Comment by lardissone** [comment]
@dylburger awesome, I'll give it a try!
