### ISSUE TITLE
[TRIGGER] Twitter

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#182]
I’d like to run a workflow on new tweets or other actions from Twitter, so I’d like to see Twitter as a trigger.

**Comment by Juslesiasru** [comment]
Would love to see it !

**Comment by Juslesiasru** [comment]
Hello Dylan, what about this feature ? Did you managed to do it ?
Thank you !

**Comment by dylburger** [comment]
@Juslesiasru triggers are a priority for us at the moment, and should be coming soon! I'll update this issue, and let y'all know on Slack, when this is ready for use.

**Comment by Juslesiasru** [comment]
Hi Dylan,

i don't know if you are working on it but i would like to tell you that this feature is a need for me and propably a lot of people.

Have a good day.

**Comment by dylburger** [comment]
We just shipped 9 sources for Twitter that run on new mentions, new likes, etc. Check out https://twitter.pipedream.com and https://pipedream.com/sources !
