### ISSUE TITLE
[ACTION] Shopify: get a single customer

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#185]
**Is there a specific app this action is for?**

Shopify

**Please provide a link to the relevant API docs for the specific service / operation.**

https://help.shopify.com/en/api/reference/customers/customer#show-2019-10

**Comment by Muaazt** [comment]
[Issue] This step is giving the below response:
![image](https://user-images.githubusercontent.com/36134250/71987235-7de4f080-3236-11ea-86b5-05585e1cf501.png)
