### ISSUE TITLE
[ACTION] Shopify Mark Order as Paid

### ISSUE THREAD

**Issue by Muaazt** [PipedreamHQ/roadmap#199]
https://help.shopify.com/en/api/reference/orders/transaction#create-2020-01

**Comment by sergioeliot2039** [comment]
Hi @Muaazt .
This is Sergio, I'm helping building actions.
I have performed changes to the Shopify "Mark Order as Paid" action as per the last feedback provided by @dylburger .
I've published said action in Pipedream at https://pipedream.com/actions/a_k6iYR2/edit
Would you mind checking this out and see if it can be closed or further amendments to the action are needed?

**Comment by sergioeliot2039** [comment]
Sorry, you can look at a sample workflow here: https://pipedream.com/@sergio/p_ZJCnAb/edit

**Comment by Muaazt** [comment]
Hi @sergioeliot2039,

This works exactly as expected, thank you!

Just a few details after testing: when marking an order that is pending as paid it must be a capture payment, the others will not work as that is only for gateways. The sale one will work if creating order and payment is one step which I don't think is possible at the moment unless you have payment gateway api access.

**Comment by sergioeliot2039** [comment]
I modified the action to include the note about using the "sale" payment requiring Payment integration, in case someone wants to use the action as a starting point. Marking this issue as closed.
