### ISSUE TITLE
[ACTION] Shopify Create Draft Order

### ISSUE THREAD

**Issue by Muaazt** [PipedreamHQ/roadmap#200]
https://help.shopify.com/en/api/reference/orders/draftorder#create-2020-01

**Comment by sergioeliot2039** [comment]
Hi @Muaazt ,
Sergio again.
This time looking for feedback on Shopify's create draft order action. A sample workflow showing that action is available at: https://pipedream.com/@sergio/p_WxCnov/edit

**Comment by sergioeliot2039** [comment]
After my internal texting, I believe this works as expected if it is considered another way feel free to reach out. Closing for now.
