### ISSUE TITLE
[APP]Flexie CRM

### ISSUE THREAD

**Issue by cuongtalentccc** [PipedreamHQ/roadmap#214]
**Name of app / service**
Flexie CRM
**Link to developer documentation**
https://flexie.io/api-docs/
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
Trigger a workflow when customer/lead fill the form or purchase the product from ThriveCart.
**Are there specific actions you'd use for this app?**
Create/Update a Lead
Create/Update a Contact
Create/Update an Account

**Comment by todsac** [comment]
I have added Flexie integration via API Key.
