### ISSUE TITLE
[APP]AWS SES

### ISSUE THREAD

**Issue by cuongtalentccc** [PipedreamHQ/roadmap#215]
**Name of app / service**
AWS SES
**Link to developer documentation**
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
For example, trigger a workflow when I receive a new email in Gmail.

**Are there specific actions you'd use for this app?**
Send an email.

**Comment by dylburger** [comment]
Example workflow: https://pipedream.com/@dylburger/send-an-email-using-amazon-ses-p_zACKnQ/edit
