### ISSUE TITLE
[ACTION] Improve Slack: POST /files.upload

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#228]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
Was able to finally wrap this Slack File upload action.
Workfow:
https://pipedream.com/@sergio/slack-file-upload-p_OKC2vx/edit
Action>
https://pipedream.com/actions/a_Q3i53x/edit
