### ISSUE TITLE
[ACTION] Improve Slack: POST /mpim.open

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#229]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://api.slack.com/methods/mpim.open
Workflow:
https://pipedream.com/@sergio/p_KwCDdW/edit

**Comment by sergioeliot2039** [comment]
Sorry, the correct workflow is at: https://pipedream.com/@sergio/p_rvC6PL/edit
