### ISSUE TITLE
Support for alphabetical order when choosing a new step

### ISSUE THREAD

**Issue by sauvegardezvous** [PipedreamHQ/roadmap#248]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
alphabetic order of apps listing

![image](https://user-images.githubusercontent.com/30205003/72197016-aada0480-33ea-11ea-8007-37ada92f98c4.png)

**Comment by dylburger** [comment]
@sauvegardezvous are you mainly interested in just scanning all the apps we have integrated, so want to see the list in alphabetical order to make that easier?

Or are you trying to find a specific app quickly?

**Comment by sauvegardezvous** [comment]
> yeah, just scanning, but indeed, if I am looking for something specific, we have the search bar. :)

**Comment by dylburger** [comment]
Yeah, for the scanning use case, I can see how alphabetical order would help. Just for context: we implement the current order to prioritize certain common apps at the top. Most users are connecting to a subset of apps, so having those apps at the top makes them easier to find.

I'm curious — if we had a public page of all apps and allowed you to see those in alphabetical order, would that help?

**Comment by sauvegardezvous** [comment]
> public page of all apps and allowed you to see those in alphabetical order, would that help? 
definitively. great idea.
 

> or directly in the step menu?
not mandatory, I will use the public page. :) 

thx

**Comment by dylburger** [comment]
Nice ok, I added a list here: https://docs.pipedream.com/apps/all-apps/
