### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/branches/{branch}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#253]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/repos/branches/#get-branch
Workflow:
https://pipedream.com/@sergio/p_aNC2O7/edit
