### ISSUE TITLE
[ACTION] Github: POST /repos/{owner}/{repo}/git/blobs

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#255]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/git/blobs/#create-a-blob
Workflow:
https://pipedream.com/@sergio/p_k2CrkN/edit
