### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/issues

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#257]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/issues/#list-issues-for-a-repository
Workflow:
https://pipedream.com/@sergio/p_brCnON/edit
