### ISSUE TITLE
[ACTION] Github: POST /repos/{owner}/{repo}/issues/{number}/comments

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#258]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/issues/comments/#create-a-comment
Workflow:
https://pipedream.com/@sergio/p_ezC7xk/edit
