### ISSUE TITLE
[ACTION] Github: /repos/{owner}/{repo}/pulls/{number}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#260]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
Get pull request***
++API docs:
https://developer.github.com/v3/pulls/#get-a-single-pull-request
++Workflow:
https://pipedream.com/@sergio/p_KwCDl2/edit
Update pull request**
++API docs:
https://developer.github.com/v3/pulls/#update-a-pull-request
++Workflow:
https://pipedream.com/@sergio/p_A2Cy5d/edit
