### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/pulls/{number}/commits

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#261]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/git/commits/#create-a-commit
Workflow:
https://pipedream.com/@sergio/p_G6C1VA/edit

**Comment by sergioeliot2039** [comment]
Correct API doc is:
https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request
