### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/pulls/{number}/merge

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#262]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged
Workflow:
https://pipedream.com/@sergio/p_LQCzjd/edit
