### ISSUE TITLE
[ACTION] Github: POST /repos/{owner}/{repo}/git/commits

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#274]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/git/commits/#create-a-commit
Workflow:
https://pipedream.com/@sergio/p_ZJCne5/edit
