### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/git/commits/{shaCode}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#275]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/git/commits/#get-a-commit
Workflow:
https://pipedream.com/@sergio/p_3nC1QL/edit
