### ISSUE TITLE
[ACTION] Github: GET /repos/{owner}/{repo}/stargazers

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#276]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/activity/starring/#list-stargazers
Workflow:
https://pipedream.com/@sergio/p_MOC2Q1/edit
