### ISSUE TITLE
[ACTION] Github: POST /repos/{owner}/{repo}/forks

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#282]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/repos/forks/#create-a-fork
Workflow:
https://pipedream.com/@sergio/p_6lCZY1/edit
