### ISSUE TITLE
[ACTION] Github: POST /repos/{owner}/{repo}/pulls

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#284]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://developer.github.com/v3/pulls/#create-a-pull-request
Workflow:
https://pipedream.com/@sergio/p_7NCe85/edit
