### ISSUE TITLE
I want to query the SQL service from a workflow

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#3]
Currently users can [send data to a SQL destination](https://docs.pipedream.com/destinations/sql/#adding-a-sql-destination) and run SQL queries from the SQL UI. I want to run SQL queries against existing data from a code step or action, for example:

```javascript
const results = await $sql.query({{
  query: "SELECT * FROM my_table"
})
```

**Comment by dylburger** [comment]
It would be nice to specify filters and sort options via object, as well, sort of like a lightweight ORM. For example if this code:

```javascript
const results = await $sql.query({
  query: "SELECT * FROM my_table",
  filter: "age > 30",
  sort: "age",
})
```

could compile to the following SQL:

```sql
SELECT * FROM my_table
WHERE age > 30
ORDER BY age
```

**Comment by cfjedimaster** [comment]
Also - there should be API support for this as well.

**Comment by dylburger** [comment]
You can now query the SQL service [using our API](https://docs.pipedream.com/destinations/sql/#running-sql-queries-via-api), and [from within workflows](https://docs.pipedream.com/destinations/sql/#running-sql-queries-from-a-workflow).

Here's an [example workflow](https://pipedream.com/@dylburger/send-results-of-pipedream-sql-query-to-google-sheets-p_YyCD6r/edit) that runs a SQL query and sends the results to a Google sheet, for example.

Let me know if y'all have any feedback or questions. Happy querying!
