### ISSUE TITLE
[APP] Google Calendar

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#30]
I'd like to connect my Google Calender account from Pipedream so I can authorize API requests in a workflow.

**Comment by anilgulecha** [comment]
Specifically, what I would like is a notification 'x' minutes prior to an event, where X is configurable.

**Comment by dylburger** [comment]
We just enabled the Google Calendar integration. Take a look at [this workflow](https://pipedream.com/@dylan/check-for-morning-meetings-send-me-an-alert-if-i-have-them-p_ZJCYW2/edit?e=1TdmF7mNduANrMrZ4O8h1JNRXJs) (specifically the `list_events_in_next_n_hours` step) for an example of how this works.

@anilgulecha we haven't created a trigger for Google Calendar yet, but this pattern of running a cron job every few minutes, and listing out events a few hours in the future, can be modified for your use case. Let me know if the code there makes sense or if you have any questions.

I'm closing this larger ticket out but please comment if you'd like to see something more specific for Google Calendar and we can add new issues to track those, too.

**Comment by anilgulecha** [comment]
thanks, I will give this a shot over the weekend.
