### ISSUE TITLE
[ACTION] Twilio: POST /Accounts/{AccountSid}/Messages

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#313]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-create-a-message&code-language=curl&code-sdk-version=json
Workflow:
https://pipedream.com/@sergio/p_BjCVWB/edit
