### ISSUE TITLE
[ACTION] Twilio: GET /Accounts/{AccountSid}/SMS/ShortCodes/{ShortCodeSid}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#319]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://www.twilio.com/docs/sms/api/short-code?code-sample=code-fetch-short-code&code-language=curl&code-sdk-version=json#fetch-a-shortcode-resource
Workflow:
https://pipedream.com/@sergio/p_3nC1GW/edit
