### ISSUE TITLE
[ACTION] Twilio: GET /Accounts/{AccountSid}/Calls

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#322]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://www.twilio.com/docs/voice/api/call-resource#fetch-a-call-resource
Workflow:
https://pipedream.com/@sergio/p_G6C1kx/edit
