### ISSUE TITLE
[ACTION] Twilio: GET /Accounts/{AccountSid}/Calls/{CallSid}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#323]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://www.twilio.com/docs/voice/api/call-resource?code-sample=code-read-multiple-call-resources&code-language=curl&code-sdk-version=json#read-multiple-call-resources
Workflow:
https://pipedream.com/@sergio/p_xMCOZ2/edit

**Comment by sergioeliot2039** [comment]
Previous workflow is for Get Account Calls (list calls)
correct one is: https://pipedream.com/@sergio/twlio-get-account-call-p_G6C1kx/edit
for getting a call given its call sid.
