### ISSUE TITLE
[ACTION] Twilio: GET /Accounts/{AccountSid}

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#326]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by sergioeliot2039** [comment]
API docs:
https://www.twilio.com/docs/usage/api/account#fetch-an-account-resource
Workflow:
https://pipedream.com/@sergio/p_RRCDK9/edit
