### ISSUE TITLE
actions : params do not popup at bottom

### ISSUE THREAD

**Issue by sauvegardezvous** [PipedreamHQ/roadmap#327]
**Describe the bug**
When I fill out the code with `params.myvariable` , no input box appears at the bottom. 

**To Reproduce**
1. click on blue button "save as reusable action"
2. edit the form. 

**Expected behavior**
showing new inputs boxes at bottom 

**Screenshots**
![image](https://user-images.githubusercontent.com/30205003/72754630-5aa33500-3b96-11ea-810b-f8aae4748622.png)

![image](https://user-images.githubusercontent.com/30205003/72754665-7ad2f400-3b96-11ea-828f-d9f8a479b463.png)

windows10 desktop 
chrome Version 79.0.3945.130 x64

**Comment by dylburger** [comment]
@sauvegardezvous you may have noticed we just made some UX changes to the app. The params form now appears at the top of code steps. Are you still able to replicate this issue?
