### ISSUE TITLE
run only one step in a workflow at once for debug

### ISSUE THREAD

**Issue by sauvegardezvous** [PipedreamHQ/roadmap#328]
**Is your feature request related to a problem? 
I am always waiting to test my code in every steps when I am building a workflow. 
I have to manipulate data and all previous steps are triggered and do things normally.
And that creates so many unwanted requests to 3rd parties apps. 

**Describe the solution you'd like**
I suggest to be able to run only one step from all steps, and get the last result available for that step.

**Do you have a workaround?**
no, and I can trigger off all others steps but I lost the result (output)

**Comparable features in other tools?**
I don't know. 

If that is not clear, let me know. thank you ,

**Comment by dylburger** [comment]
@sauvegardezvous we're tracking this use case in #68 . I'm closing this ticket as a duplicate, but adding your specific comments as a new comment in that ticket so we have a record of it.
