### ISSUE TITLE
[APP]Pushover

### ISSUE THREAD

**Issue by cuongtalentccc** [PipedreamHQ/roadmap#333]
**Name of app / service**
Pushover
**Link to developer documentation**
https://pushover.net/api#messages
**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Pushing Messages (https://pushover.net/api#messages)
Create Subscription (https://pushover.net/api/subscriptions)

**Comment by dylburger** [comment]
@cuongtalentccc Pushover is actually already integrated, check out [this example workflow](https://pipedream.com/@dylan/pushover-example-p_rvC2Me/edit). Would you mind giving that a try and letting me know if that works for you?
