### ISSUE TITLE
[ACTION] Backlog issue tracker

### ISSUE THREAD

**Issue by alschytte** [PipedreamHQ/roadmap#334]
[NuLab Backlog](https://developer.nulab.com/) is an excellent issue tracker

[API spec](https://developer.nulab.com/docs/backlog/#backlog-api-overview)

**Comment by dylburger** [comment]
Hi @alschytte , thanks for the request. Just to confirm, would you like us to integrate NuLab as a connected app on Pipedream? 

https://docs.pipedream.com/apps/all-apps/

**Comment by todsac** [comment]
I have integrated Nulab Backlog.  We are having an issue with the Oauth integration so the API Key version is the one that is live for now.  Please let us know if you have any issues.

**Comment by todsac** [comment]
Updated to include OAuth 2.0 integration
