### ISSUE TITLE
[ACTION] Zoom: Create Registrant

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/roadmap#351]
https://marketplace.zoom.us/docs/api-reference/introduction

**Comment by sergioeliot2039** [comment]
This may refer to creating a registrant for a meeting or a webinar, which are different endpoints.
Here is a Workflow for adding the registrant into a meeting:
https://pipedream.com/@sergio/p_QPC7xL/edit
Into a webinar:
https://pipedream.com/@sergio/p_A2Cb6D/edit
Unable to test completely -- the meeting host must be a paid user
https://devforum.zoom.us/t/add-meeting-registrant-api/7082/4
webinar endpoints are for paid plans too:
Prerequisites:
Pro or higher plan with a Webinar Add-on.
