### ISSUE TITLE
[ACTION] Zoom:  Create users

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/roadmap#356]
https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate

**Comment by sergioeliot2039** [comment]
Workflow:
https://pipedream.com/@sergio/p_JZCY1a/edit

**Comment by sergioeliot2039** [comment]
This is working now with the Zoom App that was authorized:
Note: I used my personal CC to enable User Management on the free plan account
