### ISSUE TITLE
[TRIGGER] Airtable

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#366]

**Comment by beadlespouse** [comment]
+1 for this - Do Slack + Zapier get around this by retrieving records on a fixed schedule, storing them, and then comparing the previous set to the new set on each retrieve? Since AT doesn't have webhooks, this seems like the obvious work around.

**Comment by dylburger** [comment]
We've shipped 4 sources for Airtable that run on new / updated records. Check them out at https://pipedream.com/sources
