### ISSUE TITLE
[FEATURE] Edit Test Event add a scrollbar to popup

### ISSUE THREAD

**Issue by mishavee** [PipedreamHQ/roadmap#380]
Currently the Edit Test Event popup doesn't have a scrollbar, see screenshot.

I spent some time attempting to scroll by clicking the vertical bar that seems to show a code outline :P 

![edit-test-event-missing-scrollbar](https://user-images.githubusercontent.com/13145938/76038927-08c83a00-5f9f-11ea-9d14-e481b879c1da.png)

**Comment by dylburger** [comment]
@mishavee this has been implemented in the newest version of the edit test event editor!
