### ISSUE TITLE
[ACTION] Shopify update product metafields

### ISSUE THREAD

**Issue by beadlespouse** [PipedreamHQ/roadmap#385]
**Is there a specific app this action is for?**
SHOPIFY

**Please provide a link to the relevant API docs for the specific service / operation.**
https://shopify.dev/docs/admin-api/rest/reference/products/product#update-2020-01

^ Shopify product API

Can we add an 'update product' action? Specifically 'update product metafields' would be great too!

Thanks

**Comment by sergioeliot2039** [comment]
The update product metafields action is a separated action from update product. meaning the endpoint for updating a product can't be used to update a product's metafield. so I created two actions.  
Please see corresponding workfows, actions here:
Update product:
Workflow> https://pipedream.com/@sergio/shopify-update-product-p_QPCZnn/edit
Action>  https://pipedream.com/actions/a_k6iK10/edit
Update metafield of product:
Workflow> https://pipedream.com/@sergio/shopify-update-metafield-of-product-p_rvCPeZ/edit
Action > https://pipedream.com/actions/a_vgi4r3/edit
Have a look and feel free to let me know any feedback and I'll check. Thanks,
Sergio.
