### ISSUE TITLE
[FEATURE] Assistive text

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/roadmap#391]
When mousing over cell items on the top right side, there is no assistive text. Specifically the icons in the attachment. I can guess what they do, but I know I guessed wrong on at least one of them.

**Comment by todsac** [comment]
![image](https://user-images.githubusercontent.com/35614146/77789169-c505a500-701f-11ea-99e9-b8e9f8908925.png)

**Comment by dylburger** [comment]
We've added labels to these icons and others in the UI. If you see others that lack labels, please let us know.

![2020-03-28 15 23 38](https://user-images.githubusercontent.com/242668/77835463-1b4f1280-710a-11ea-89d3-de33af1de5ad.gif)
