### ISSUE TITLE
[ACTION]Create a new DNS record for a zone (Cloudflare)

### ISSUE THREAD

**Issue by cuongthachHQ** [PipedreamHQ/roadmap#393]
**Is there a specific app this action is for?**
Cloudflare
**Please provide a link to the relevant API docs for the specific service / operation.**
https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

**Comment by sergioeliot2039** [comment]
Hi there, @cuong-thach 
Action for creating a new DNS record for a zone on Cloudflare should be ready, could you please have a look and let us know if there's any issue?
Workflow:
https://pipedream.com/@sergio/cloudflare-create-dns-record-p_dDCaxY/edit
Action:
https://pipedream.com/actions/a_K5iLqd/edit
Thanks!
Sergio
