### ISSUE TITLE
[ACTION] Google Sheets: Find a Row

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#401]
Given a sheet, column name, and column value, return the row number(s) if a row with that value is found, else return undefined.

Similar action: return _first_ row with a matching value in a column, instead of an array of rows.

**Comment by sergioeliot2039** [comment]
For the first action, getting the row numbers if there's a match in value at the specified column
workflow > https://pipedream.com/@sergio/google-drive-find-rows-p_5VCkmY/edit
action> https://pipedream.com/actions/a_0Mio8a/edit

For the second action, getting the first row if there's a match in value at the specified column
workflow> https://pipedream.com/@sergio/google-drive-find-row-p_6lC9Kx/edit
action> https://pipedream.com/actions/a_8Ki7Ve/edit

All these actions look good when testing, if you find anything please let me know and I'll review. Thanks!
