### ISSUE TITLE
[FEATURE] Add workflow name to original_context

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/roadmap#416]
**Is your feature request related to a problem? Please describe.**
The `original_context` object passed to the error workflow has the workflow id that caused the issue. It should also contain the name of the workflow. I'm assuming there is some way to get this name via code, but it should just be passed in.

**Describe the solution you'd like**
Add workflow_name to original_context.

**Do you have a workaround?**
No. I assume there's a way to do it though. :)

**Comment by dylburger** [comment]
@cfjedimaster thanks for the request! We're tracking this at #412 .

**Comment by cfjedimaster** [comment]
One thing though - that issue relates to the email generated by the workflow. That is a good idea and should be done, but for folks who do their own error handling, or modify the workflow etc, it would be helpful to have this value. Basically I'm saying if you add some code to the error workflow to fix #412, I'd still want *this* particular feature done too. :)

**Comment by dylburger** [comment]
@cfjedimaster yes I understand the distinction - we'll likely solve this by including the name in the original_context, or perhaps allowing you to access metadata on your own workflows via API.

We mainly just try to consolidate issues we know will be tackled by the same work and reference them in a single ticket. I also updated that ticket name to reflect your use case.
