### ISSUE TITLE
[BUG] When adding a new collaborator, the email address doesn't show up (on first load)

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/roadmap#422]
**Describe the bug**
When I've invited someone to a workflow, they don't show up as invited until I reload the page.

**To Reproduce**
1. Go to a workflow's settings.
2. Enter an email address and hit add.
3. No email is shown.
4. Reload and now it shows up as invited.

**Expected behavior**
For it to be shown immediately.

**Desktop (please complete the following information):**
Edge, latest

**Comment by dylburger** [comment]
Should be fixed. You can also now add collaborators by username.
