### ISSUE TITLE
403 issue with Reddit: Get subreddits/mine/where

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/roadmap#428]
**Describe the bug**
I've been using the Reddit actions in another workflow and then tried it again in a new one. This time I wanted to get my subscribed subreddits so I added the action: "Get subreddits/mine/where". For where I used the value "subscriber". When I execute it, I get a 403 unauthorized exception. I've confirmed in the auth section it has my account connected.

**To Reproduce**
1. Make a new trigger
2. Add reddit/Get subreddits mine
3. Set where to subscriber
4. Connect your account
5. Run it

**Expected behavior**
My subscribed subreddits.

**Screenshots**

![image](https://user-images.githubusercontent.com/393660/79669734-436ae800-8183-11ea-9a17-cdcd5f9deb3e.png)

**Comment by cfjedimaster** [comment]
It looks like you need to add the scope, mysubreddits.

https://www.reddit.com/dev/api/#GET_subreddits_mine_{where}

Currently the app only asks for account, history, identity, read

**Comment by dylburger** [comment]
@cfjedimaster would you mind re-authorizing Reddit and trying again? In the `auth` section of the code step, unlink your account, connect account again, choose **New** and go through the OAuth authorization process again.

You'll still have an old connected account under https://pipedream.com/apps tied to your old Reddit auth (sans `mysubreddits`). You can keep that or delete it and link other Reddit code steps with the new auth provision, so you only have a single one.

**Comment by cfjedimaster** [comment]
Confirmed. Just curious - was I right?

**Comment by dylburger** [comment]
Yep! Thanks for confirming.
