### ISSUE TITLE
[APP] You Need A Budget (YNAB)

### ISSUE THREAD

**Issue by RohanNagar** [PipedreamHQ/roadmap#456]
**Name of app / service**
You Need A Budget (YNAB)

**Link to developer documentation**
https://api.youneedabudget.com

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Not blocking, workaround is directly using the API with Node.js

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Some ideas for actions, this is not an exhaustive list:
- Create transaction
- Get transactions
- Get accounts
- Clear transaction

**Comment by todsac** [comment]
This app has been added to Pipedream.
