### ISSUE TITLE
Button for updating Action Version

### ISSUE THREAD

**Issue by raunakk** [PipedreamHQ/roadmap#468]
**Is your feature request related to a problem? Please describe.**
Whenever I need to update the code within an action, I need to go to my workflow and delete and replace the steps where that action is called. I also need to then specify all the params again.  

**Describe the solution you'd like**
A button in steps with actions where you can "Refresh" the code and the new code shows up with updated params. Newly added params should be blank, persisted params should remain as they are. 

**Do you have a workaround?**
Workaround is to delete the step and add the same action again and specify all the params. 

**Comparable features in other tools?**
Is this feature or one like it available in another platform? If so, we'd love to hear what you like about that implementation.

**Additional context**

**Comment by dylburger** [comment]
Thank you for this request @raunakk . We have an open feature request on this at #438 . I'm closing this, if you wouldn't mind following that original issue.

**Comment by raunakk** [comment]
Thanks!
