### ISSUE TITLE
Bug: allow $respond to return custom Content-Type header

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#47]
Right now, Pipedream appends `chartset=utf-8` to the `Content-Type` header returned with any HTTP response issued with`$respond`, even if I provide my own custom `Content-Type` header.

**Comment by jveres** [comment]
This is expected to return an image, a single red pixel.
```
$respond({
    status: 200,
    headers: {'Content-Type': 'image/png'}, 
    body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==', 'base64').toString()
})
```
Not sure if `charset=utf-8` is the real issue, but `Content-Length` mismatches as well.

**Comment by casret** [comment]
The body param will now correctly handle Buffer objects (do not call convert it to a string).  

A pixel is too small for me too see, but:
https://pipedream.com/new?template=p_95CBwD
renders:

https://enbt2igvz16wu8n.m.pipedream.net/?pipedream_response=1
