### ISSUE TITLE
[BUG] Airtable Get Records Action does not work with sort param

### ISSUE THREAD

**Issue by raunakk** [PipedreamHQ/roadmap#473]
**Describe the bug**
When the sort param is passed to the Airtable Get Records Action, it returns a 422 error. 

**To Reproduce**
1. Create a new workflow with List Records Action from Airtable ( /GET lists records in a table)
2. Specify a column to sort on
3. Send a test event to execute the action

ErrorRequest failed with status code 422
    at null.createError (/tmp/ee/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/tmp/ee/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/ee/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at null.endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
**Expected behavior**

The url created has: 
&sort[]=%7B%22field%22:%22Created%22,%22direction%22:%22asc%22%7D
where as, as per the documentation, it should have:
sort%5B0%5D%5Bfield%5D=Created&sort%5B0%5D%5Bdirection%5D=asc

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dylburger** [comment]
Thank you for raising this @raunakk . We're looking into this and will fix ASAP.

**Comment by dylburger** [comment]
Hi @raunakk , we've shipped a new version of this action that should implement a fix for the `sort` param. 

Would you mind adding the **List Records** action to your workflow, and give it another try? You can also copy [this example workflow](https://pipedream.com/@dylan/airtable-list-records-p_ezC9BA/edit), which exposes a sample value for the sort param, with an example **Name** field.

Let me know if that doesn't work and I'll look into the issue further.
