### ISSUE TITLE
[FEATURE] TypeScript intellisense

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/roadmap#482]
**Is your feature request related to a problem? Please describe.**

I think TypeScript intellisense could be really useful. I noticed you’re using Monaco’s editor, so I think that wouldn’t be the most difficult. It would be nice to know what fields the event has, etc. The autocomplete would be great.

**Describe the solution you'd like**

I haven’t used Monaco before, but from a quick lookup online, it seems like you could to it using monaco.typescript.addExtraLib

**Comment by dylburger** [comment]
Intellisense is already supported in the editor, which supports autocomplete.
