### ISSUE TITLE
Chargify

### ISSUE THREAD

**Issue by Sathya-B** [PipedreamHQ/roadmap#486]
Chargify

https://reference.chargify.com/v1/basics/introduction

If the app is integrated, we could use OAuth instead of API key. Since we have lots of $ being transacted in the account, Oauth is a preferred way of integration.

We would like to use chargify api to create custom metadata for a site and also retrieve custom metadata for a specific subscription

**Comment by dylburger** [comment]
Chargify has been integrated. See [this example workflow](https://pipedream.com/@dylburger/chargify-example-workflow-p_A2C2wK/edit).
