### ISSUE TITLE
MongoDB Destination

### ISSUE THREAD

**Issue by kantle** [PipedreamHQ/roadmap#59]
**Name of app / service**
MongoDB

**Link to developer documentation**
https://docs.mongodb.com/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
No, in theory a user could use a node block to instantiate the connection and perform writes...but given the current limits on workflow execution time the connection overhead could cause more timeouts.

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
Setting DB Writes as a trigger would be interesting, but not something we need right now.

**Are there specific actions you'd use for this app?**
Storing data from received Webhooks from 3rd party apps.

**Comment by dylburger** [comment]
@kantle @cuongtalentccc we just added an app for MongoDB. Here's an example workflow of me using an action to insert a single document into a collection (streaming HTTP requests directly to Mongo): https://pipedream.com/@dylburger/stream-http-requests-into-mongodb-p_KwCD97/edit .

Let me know if you have any other feedback or questions!
