### ISSUE TITLE
[TRIGGER] RSS / Atom

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#6]
I'd like to trigger a workflow on changes to an RSS feed, running the workflow for each new item the feed produces.

**Comment by psavkar** [comment]
For the time being, anyone who wants to process "new" items from an RSS feed can fork this workflow and use it as a starting point:

https://pipedream.com/@pravin/process-new-items-from-an-rss-feed-on-a-schedule-p_brC5qv/readme

`steps.rss` will retrieves the items from an RSS feed on a schedule and export any "new" items that you can reference in any subsequent code steps. If no new items are detected, workflow execution will end.

**Comment by dylburger** [comment]
You can now trigger a workflow directly from an RSS feed. Details here: https://rss.pipedream.com/
