### ISSUE TITLE
Support HTTP payloads larger than 100KB

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#7]
Currently, [workflows with HTTP triggers can support max payloads of 100KB](https://docs.pipedream.com/limits/#http-triggers). I'd like to run workflows on larger payloads.

**Comment by dylburger** [comment]
Another user was trying to send an email with a larger attachment, and encountered a 413 error tied because of the payload limit.

**Comment by dylburger** [comment]
Attachments in emails are currently limited to roughly 50KB, since the attachment is included in the raw event (the raw email), and also parsed and included in Pipedream's `event.attachments` variable. Since they're included twice, the sum of attachments must be no more than 50KB to match the overall 100KB limit.

**Comment by dylburger** [comment]
@dturton @mildmojo we've raised the limit on HTTP payloads to 512KB, and 256KB for email payloads. This is a short-term fix to support larger plaintext and email attachments - many users were sending payloads just above the original 100KB limit, so we're hoping this will help.

We're still considering ways to support even larger payloads, so let me know if you've got a specific use case for payloads larger than 512KB and we can discuss. For now, I'm closing this ticket but I'm happy to open another, more targeted issue for that use case.

**Comment by mildmojo** [comment]
Thanks, this addresses my use case. I think my larger HTTP payloads are in the 100-150KB range.
