### ISSUE TITLE
Airtable Update Records Action: support updates for more than 10 records

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#82]

**Comment by sergioeliot2039** [comment]
Hi there, I have prepared a new version of Airtable's Update records endpoint, it accepts n records, iterates over them and hit said endpoint in batches of top 10 records.
Workflow>
https://pipedream.com/@sergio/airtable-update-n-records-p_V9C3wx/edit
ACtion>
https://pipedream.com/actions/a_xqiq4k/edit
In my testing works seamlessly, but if you notice anything please just let me know. Thx
