### ISSUE TITLE
[APP] Telstra Messaging API

### ISSUE THREAD

**Issue by ajlowndes** [PipedreamHQ/roadmap#92]
**Name of app / service**
Telstra Messaging API

**Link to developer documentation**
https://dev.telstra.com/content/messaging-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Don't have a workaround at the moment. I use Telstra Messaging API instead of Twilio but I cannot find a way to modify the "twilio" pipedream integration to work with this instead. 

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
I want to modify the "Relay a message from a Twilio SMS webhook to another phone number" to work with Telstra Messaging API instead of Twilio.

**Are there specific actions you'd use for this app?**
None other than the above (/unsure).

**Comment by dylburger** [comment]
@ajlowndes I setup the Messaging API as a connected account in Pipedream. Here's an example workflow that sends an SMS: https://pipedream.com/@dylburger/telstra-send-sms-test-p_pWC15M/edit .

This is the default code that you'll get when you add a new step, select Telstra as an app, and "Run Node.js code with Telstra").

You may already be aware of this, but the Messaging API has an interesting OAuth integration. There's no app managed by Pipedream where you go through the traditional OAuth flow and let us authorize requests on your behalf. Instead, you [create your own app, which generates a client ID / secret](https://dev.telstra.com/content/messaging-api#section/Getting-Access-to-the-API). 

You'll be asked to enter that client ID / secret when you connect your Telstra account, and we'll take care of generating the access tokens (the code sample shows you how that works).

Let me know if this works for you and if you have any additional feedback / questions!

**Comment by ajlowndes** [comment]
Awesome, thanks!
