### ISSUE TITLE
I'd like to see my quota usage to date

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#97]
Pipedream sets a [daily quota on workflow runtime](https://docs.pipedream.com/limits/#workflows), and sends emails when you reach 80% and 100% of that daily usage.

I'd like to know what my level of usage is before I hit those thresholds, e.g. in a dashboard or settings somewhere I can view in a self-service way.

**Comment by tjk** [comment]
Can now see this by going to https://pipedream.com/settings/billing!
