### ISSUE TITLE
[APP] Twilio Programmable Fax API

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/roadmap#98]
https://www.twilio.com/docs/fax/send

**Comment by sauvegardezvous** [comment]
**Name of app / service**
programmable fax from Twilio 

**Link to developer documentation**
https://www.twilio.com/docs/fax
https://www.twilio.com/docs/fax/send
https://www.twilio.com/docs/libraries/node

**Is lack of support preventing you from building workflows, or do you have a workaround?**
nope. 

**Are there specific app events you'd like to see as triggers (event that run a workflow)?**
trigger a workflow when I receive a fax 

**Are there specific actions you'd use for this app?**
send a fax
